#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p desert-cleaner 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p desert-cleaner /usr/share/desert-cleaner
fi

# End automatically added section
